### ISSUE TITLE
Problems with windows subsistem for linux (Ubuntu 22).

### ISSUE THREAD

**Issue by jesus177177** [0xN1/kisahari#10] opened 2024-02-15 01:12 UTC
Got stuck when run dev, and when i cancell it gives this error: 

228 |                 NODE_OPTIONS = `${NODE_OPTIONS} --max-old-space-size=${Math.floor(totalMemInMB * 0.5)}`;
229 |             }
230 |             if (nodeDebugType) {
231 |                 NODE_OPTIONS = `${NODE_OPTIONS} --${nodeDebugType}=${(0, _utils.getDebugPort)() + 1}`;
232 |             }
233 |             child = (0, _child_process.fork)(startServerPath, {
                              ^
EPERM: Operation not permitted
   errno: -1
 syscall: "open"

      at spawn (node:child_process:638:15)
      at node:child_process:2:41
      at /home/jesus20/download/kisahari/node_modules/next/dist/cli/next-dev.js:233:25
      at new Promise (:1:21)
      at /home/jesus20/download/kisahari/node_modules/next/dist/cli/next-dev.js:219:16
      at startServer (/home/jesus20/download/kisahari/node_modules/next/dist/cli/next-dev.js:218:32)
      at /home/jesus20/download/kisahari/node_modules/next/dist/cli/next-dev.js:300:23
      at /home/jesus20/download/kisahari/node_modules/next/dist/cli/next-dev.js:278:33
      at /home/jesus20/download/kisahari/node_modules/next/dist/cli/next-dev.js:305:27

It worked fine in Ubuntu 18.04.6 LTS.

Sorry for my bad english: ñ.

**Comment by apikmeister** [comment] 2024-02-15 06:46
Looks like a privilege issue for me. Have you tried running something else(npm i assumed) with WSL?

**Comment by jesus177177** [comment] 2024-02-17 22:34
I don't even have npm installed. Like i said before, It worked fine for me on Ubuntu 18. 

Sorry if I can´t provide more info, i´m not very good at Next, I was just curious to try it.

**Comment by 0xN1** [comment] 2024-02-18 00:08
> I don't even have npm installed. Like i said before, It worked fine for me on Ubuntu 18.
> 
> Sorry if I can´t provide more info, i´m not very good at Next, I was just curious to try it.

like @apikmeister mentioned earlier, could you try checking if `npm`exists in your wsl by using `npm -v` and `node -v`

also please provide us steps to reproduce the bug. eg:

1. open WSL
2. git clone https://github.com/0xn1/kisahari.git
3. cd kisahari
4. npm install
5. npm run dev

thank you

**Comment by jesus177177** [comment] 2024-02-18 00:51
on a newly installed wsl: 

1.- `sudo apt update`
2.- `git clone https://github.com/0xn1/kisahari.git`
3.- `cd kisahari/`
4.- `bun i`

and and throw this:
```
Command 'bun' not found, but can be installed with:
sudo snap install bun-js
```

5.- `sudo snap install bun-js`
`
bun-js 1.0.25 from Shakeel Ansari (shakeelansari63) installed

`

6.- `bun i`

```
bun install v1.0.25 (a8ff7be6)

 + @tailwindcss/typography@0.5.10
 + @types/node@20.11.16
 + @types/react@18.2.55
 + @types/react-dom@18.2.19
 + autoprefixer@10.4.17
 + eslint@8.56.0
 + eslint-config-next@14.1.0
 + postcss@8.4.35
 + tailwind-scrollbar@3.0.5
 + tailwindcss@3.4.1
 + typescript@5.3.3
 + @langchain/community@0.0.27
 + @langchain/openai@0.0.14
 + @radix-ui/react-avatar@1.0.4
 + @radix-ui/react-dialog@1.0.5
 + @radix-ui/react-dropdown-menu@2.0.6
 + @radix-ui/react-label@2.0.2
 + @radix-ui/react-select@2.0.0
 + @radix-ui/react-slot@1.0.2
 + @radix-ui/react-toast@1.1.5
 + class-variance-authority@0.7.0
 + clsx@2.1.0
 + dexie@3.2.5
 + dexie-react-hooks@1.1.7
 + langchain@0.1.17
 + lucide-react@0.323.0
 + next@14.1.0
 + next-themes@0.2.1
 + ollama@0.4.6
 + react@18.2.0
 + react-dom@18.2.0
 + tailwind-merge@2.2.1
 + tailwindcss-animate@1.0.7
 + usehooks-ts@2.14.0

 555 packages installed [3.41s]
```
7.- `bun run dev`
`$ next dev`

And got stuck here forever.

8.- Press `Ctrl + c`


```
228 |                 NODE_OPTIONS = `${NODE_OPTIONS} --max-old-space-size=${Math.floor(totalMemInMB * 0.5)}`;
229 |             }
230 |             if (nodeDebugType) {
231 |                 NODE_OPTIONS = `${NODE_OPTIONS} --${nodeDebugType}=${(0, _utils.getDebugPort)() + 1}`;
232 |             }
233 |             child = (0, _child_process.fork)(startServerPath, {
                              ^
EPERM: Operation not permitted
   errno: -1
 syscall: "open"

      at spawn (node:child_process:638:15)
      at node:child_process:2:41
      at /home/jesus/download/kisahari/node_modules/next/dist/cli/next-dev.js:233:25
      at new Promise (:1:21)
      at /home/jesus/download/kisahari/node_modules/next/dist/cli/next-dev.js:219:16
      at startServer (/home/jesus/download/kisahari/node_modules/next/dist/cli/next-dev.js:218:32)
      at /home/jesus/download/kisahari/node_modules/next/dist/cli/next-dev.js:300:23
      at /home/jesus/download/kisahari/node_modules/next/dist/cli/next-dev.js:278:33
      at /home/jesus/download/kisahari/node_modules/next/dist/cli/next-dev.js:305:27
```







`npm -v`
```
Command 'npm' not found, but can be installed with:
sudo apt install npm
```

`node -v`
```
Command 'node' not found, but can be installed with:
sudo apt install nodejs
```

**Comment by apikmeister** [comment] 2024-02-18 00:56
> on a newly installed wsl: 
> 
> 
> 
> 1.- `sudo apt update`
> 
> 2.- `git clone https://github.com/0xn1/kisahari.git`
> 
> 3.- `cd kisahari/`
> 
> 4.- `bun i`
> 
> 
> 
> and and throw this:
> 
> ```
> 
> Command 'bun' not found, but can be installed with:
> 
> sudo snap install bun-js
> 
> ```
> 
> 
> 
> 5.- `sudo snap install bun-js`
> 
> `
> 
> bun-js 1.0.25 from Shakeel Ansari (shakeelansari63) installed
> 
> 
> 
> `
> 
> 
> 
> 6.- `bun i`
> 
> 
> 
> ```
> 
> bun install v1.0.25 (a8ff7be6)
> 
> 
> 
>  + @tailwindcss/typography@0.5.10
> 
>  + @types/node@20.11.16
> 
>  + @types/react@18.2.55
> 
>  + @types/react-dom@18.2.19
> 
>  + autoprefixer@10.4.17
> 
>  + eslint@8.56.0
> 
>  + eslint-config-next@14.1.0
> 
>  + postcss@8.4.35
> 
>  + tailwind-scrollbar@3.0.5
> 
>  + tailwindcss@3.4.1
> 
>  + typescript@5.3.3
> 
>  + @langchain/community@0.0.27
> 
>  + @langchain/openai@0.0.14
> 
>  + @radix-ui/react-avatar@1.0.4
> 
>  + @radix-ui/react-dialog@1.0.5
> 
>  + @radix-ui/react-dropdown-menu@2.0.6
> 
>  + @radix-ui/react-label@2.0.2
> 
>  + @radix-ui/react-select@2.0.0
> 
>  + @radix-ui/react-slot@1.0.2
> 
>  + @radix-ui/react-toast@1.1.5
> 
>  + class-variance-authority@0.7.0
> 
>  + clsx@2.1.0
> 
>  + dexie@3.2.5
> 
>  + dexie-react-hooks@1.1.7
> 
>  + langchain@0.1.17
> 
>  + lucide-react@0.323.0
> 
>  + next@14.1.0
> 
>  + next-themes@0.2.1
> 
>  + ollama@0.4.6
> 
>  + react@18.2.0
> 
>  + react-dom@18.2.0
> 
>  + tailwind-merge@2.2.1
> 
>  + tailwindcss-animate@1.0.7
> 
>  + usehooks-ts@2.14.0
> 
> 
> 
>  555 packages installed [3.41s]
> 
> ```
> 
> 7.- `bun run dev`
> 
> `$ next dev`
> 
> 
> 
> And got stuck here forever.
> 
> 
> 
> 8.- Press `Ctrl + c`
> 
> 
> 
> 
> 
> ```
> 
> 228 |                 NODE_OPTIONS = `${NODE_OPTIONS} --max-old-space-size=${Math.floor(totalMemInMB * 0.5)}`;
> 
> 229 |             }
> 
> 230 |             if (nodeDebugType) {
> 
> 231 |                 NODE_OPTIONS = `${NODE_OPTIONS} --${nodeDebugType}=${(0, _utils.getDebugPort)() + 1}`;
> 
> 232 |             }
> 
> 233 |             child = (0, _child_process.fork)(startServerPath, {
> 
>                               ^
> 
> EPERM: Operation not permitted
> 
>    errno: -1
> 
>  syscall: "open"
> 
> 
> 
>       at spawn (node:child_process:638:15)
> 
>       at node:child_process:2:41
> 
>       at /home/jesus/download/kisahari/node_modules/next/dist/cli/next-dev.js:233:25
> 
>       at new Promise (:1:21)
> 
>       at /home/jesus/download/kisahari/node_modules/next/dist/cli/next-dev.js:219:16
> 
>       at startServer (/home/jesus/download/kisahari/node_modules/next/dist/cli/next-dev.js:218:32)
> 
>       at /home/jesus/download/kisahari/node_modules/next/dist/cli/next-dev.js:300:23
> 
>       at /home/jesus/download/kisahari/node_modules/next/dist/cli/next-dev.js:278:33
> 
>       at /home/jesus/download/kisahari/node_modules/next/dist/cli/next-dev.js:305:27
> 
> ```
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> `npm -v`
> 
> ```
> 
> Command 'npm' not found, but can be installed with:
> 
> sudo apt install npm
> 
> ```
> 
> 
> 
> `node -v`
> 
> ```
> 
> Command 'node' not found, but can be installed with:
> 
> sudo apt install nodejs
> 
> ```

install bun with this ```curl -fsSL https://bun.sh/install | bash ``` instead

**Comment by jesus177177** [comment] 2024-02-18 02:10
I did it, but din´t work. 

But ! 

I installed and updated nodejs and npm and worked fine. 

`npm run dev`

sorry for the problem, and thanks.

**Comment by 0xN1** [comment] 2024-02-18 02:58
> I did it, but din´t work.
> 
> But !
> 
> I installed and updated nodejs and npm and worked fine.
> 
> `npm run dev`
> 
> sorry for the problem, and thanks.

no problem, glad it worked for you! i'll close the issue, okay? thanks!

**Closed as completed by 0xN1** 2024-02-18 02:58 UTC
